name: cloud-mysql
type: db
title: Cloud MySQL
external: true
options:
- version: 5.5
- version: 5.6
- version: 5.7
- version: 8
labels:
- mysql
integrations:
- name: db
  title: Managed DB service
  type: db
  required: true
  option: mysql
