name: cloud-mysql
icon: mysql
type: db
title: Cloud MySQL
external: true
options:
- version: '5.5'
- version: '5.6'
- version: '5.7'
- version: '8'
labels:
- mysql
database:
  type: mysql
  db:
    name: '{{app.name}}_{{instance.name}}'
    charset: 'utf8mb4'
    collation: 'utf8mb4_unicode_ci'    
  user:
    name: '{{app.name}}_{{instance.name}}'
    password: '{{password}}'
tokens:
- name: password
  generate:
    regex: '[0-9a-z-]{32}'
